name: gpt
channels:
  - fastai
  - pytorch
  - conda-forge
  - defaults
  - powerai
  - roccqqck
dependencies:
  - jsonnet
  - ipykernel
  - python
  - pip
  - fastai
  - pytorch>=1.3
  - regex
  - langdetect
  - tensorboardX
  - cudatoolkit
  - tensorboard
  - tensorflow>=2
  - uvicorn
  - terraform
  - google-cloud-sdk
  - tar 
  - zstd
  - pip:
    - pyTelegramBotAPI
    - pysocks
    - tendo
    - schedule
    - fastapi>=0.41
    - youtokentome
    - requests
    - rupo
    - transitions
    - mezmorize
    - transformers[torch]==2.10
